server:
  port: 9091
spring:
  application:
    name: ORDER-SERVICE
  cloud:
    discovery:
      enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:9092}



  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb?createDatabaseIfNotExist=true
    username: root
    password: deependra
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true





management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always



resilience4j:
  circuitbreaker:
    instances:
      PAYMENT-SERVICE:
        registerHealthIndicator: true
        slidingWindowSize: 2
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        record-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.net.ConnectException
          - com.shopping.order_service.exception.CustomException
          - java.lang.IllegalStateException
          - feign.RetryableException
          - java.net.SocketTimeoutException
          - feign.FeignException
