server:
  port: 9091
spring:
  application:
    name: ORDER-SERVICE
  cloud:
    config:
      uri: http://localhost:9092


  datasource:
    url: jdbc:mysql://localhost:3306/orderdb?createDatabaseIfNotExist=true
    username: root
    password: deependra
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

#management:
#  tracing:
#    sampling:
#      probability: 1.0  # Trace all requests
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans
#
#logging:
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"







